CREATE TABLE User(
	userID INT NOT NULL AUTO_INCREMENT,
	firstName VARCHAR(100),
	lastName VARCHAR(100),
	email VARCHAR(100),
	PRIMARY KEY(userID)
);

CREATE TABLE PhoneNumber(
	numberID INT NOT NULL AUTO_INCREMENT,
	userID INT, 
	home VARCHAR(100),
	mobile VARCHAR(100)
	PRIMARY KEY(numberID),
	FOREIGN KEY (userID) REFERENCES User(userID)
);

CREATE TABLE Address(
	addressID INT NOT NULL AUTOINCREMENT,
	userID INT, 
	  ZIP           VARCHAR(12),
    STREET        VARCHAR(200),
    CITY          VARCHAR(100),
    STATE         VARCHAR(100),
    PRIMARY KEY (ZIP),
    FOREIGN KEY (userID) REFERENCES User(userID)
);